### ISSUE TITLE
Feature Request - Detect low audio levels, use them for scene detection

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#10]
As we talked about in our Twitter messages, it would be nice to add sound level detection.

I assume the scanner would add db level to the JSON file for the splitter to use to detect scenes. 

There will be more config values to tweak the overlap between black screen and no audio, as well as a length threshold like you have for black screen detection now. 

It's probably best to make it an optional flag which is disabled by default until it can be tested and good values can be found for the config.

**Comment by MoeFwacky** [comment]
I've added audio detection into the scanner. This gives a loudness value and a Boolean for if silence is detected in the frame according to the value set in the config. It doesn't appear to greatly affect the processing time at all on my end. I'll be adding the check into the scene splitter function next to see how it works for cutting up commercials.

**Comment by MoeFwacky** [comment]
I've added audio level support to the scene splitter. So far in testing it's worked pretty well.

**Comment by dege13** [comment]
One of my videos resulted in a bunch of scenes detected where it is all just 4 to 11 seconds of blue. Would adding blue as a secondary scene splitter help resolve this?
<img width="992" alt="image" src="https://user-images.githubusercontent.com/3587941/236455455-4bb35355-8c88-4750-be9a-6d44a9ae30fe.png">

If it helps, two blues I commonly see are:
RGB 2-6-254
![image](https://user-images.githubusercontent.com/3587941/236456102-40782621-1476-4359-958a-5a47ee16b60c.png)

RGB 72-47-194 
![image](https://user-images.githubusercontent.com/3587941/236456060-394551ee-c921-495e-86af-e046c600ed29.png)

**Comment by MoeFwacky** [comment]
I've updated the audio level support and have set it up to determine the silence threshold at the 35th percentile of the min/max range (excluding -Infinity). It hit fairly accurate, but it does miss cuts in which audio plays over the fade. Still the margin of error appears to be less in testing so far. I have more files to run it through, but I think it's in pretty good shape.
