### ISSUE TITLE
Feature Request - Normalize sound levels

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#11]
I know you said you use another tool to normalize the audio. I figured it would help me, and possibly you, if the feature was added into the splitting process. 

As usual, feel free to close it if this is not something you want to do.

**Comment by MoeFwacky** [comment]
This feature was added in [this update](https://github.com/MoeFwacky/videotools/commit/8c4f117a2673a75a3d821947f4cb1af227563a42)

**Comment by MoeFwacky** [comment]
I added it in as its own step, since sometimes there's still a need to split or merge files and this keeps audio normalization to be used on files after those operations have taken place
