### ISSUE TITLE
Missing new requirement - pydub

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#13]
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::o     o  o      8                 ooooo               8        ::
::8     8         8                   8                 8        ::
::8     8 o8 .oPYo8 .oPYo. .oPYo.     8   .oPYo. .oPYo. 8 .oPYo. ::
::`b   d'  8 8    8 8oooo8 8    8     8   8    8 8    8 8 Yb..   ::
:: `b d'   8 8    8 8.     8    8     8   8    8 8    8 8   'Yb. ::
::  `8'    8 `YooP' `Yooo' `YooP'     8   `YooP' `YooP' 8 `YooP' ::
:::::..::::..:.....::.....::.....:::::..:::.....::.....:..:.....:::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Traceback (most recent call last):
  File "c:\videotools\videotools.py", line 41, in <module>
    import videoscanner
  File "c:\videotools\videoscanner.py", line 18, in <module>
    from pydub import AudioSegment, silence
ModuleNotFoundError: No module named 'pydub'

**Comment by MoeFwacky** [comment]
added pydub to the requirements.txt file
