### ISSUE TITLE
Scanner - audio_segment.py - pydub.exceptions.CouldntDecodeError: Unable to process >4GB files

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#14]
There seems to be a limit on files over 4Gb with pydub. A quick search online implies that this size limit may be the file in memory, not the actual source file on disk, but I do not know for sure.

https://github.com/jiaaro/pydub/blob/master/pydub/audio_segment.py#L140

Error text:
```
python c:\videotools\videotools.py -sc -d C:\\videotools\\1-input
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::o     o  o      8                 ooooo               8        ::
::8     8         8                   8                 8        ::
::8     8 o8 .oPYo8 .oPYo. .oPYo.     8   .oPYo. .oPYo. 8 .oPYo. ::
::`b   d'  8 8    8 8oooo8 8    8     8   8    8 8    8 8 Yb..   ::
:: `b d'   8 8    8 8.     8    8     8   8    8 8    8 8   'Yb. ::
::  `8'    8 `YooP' `Yooo' `YooP'     8   `YooP' `YooP' 8 `YooP' ::
:::::..::::..:.....::.....::.....:::::..:::.....::.....:..:.....:::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
: ___  __              ___     __   __                  ___  __  ::
:|__  |__)  /\   |\/| |__     /__` /  `  /\  |\ | |\ | |__  |__) ::
:|    |  \ /~~\  |  | |___    .__/ \__, /~~\ | \| | \| |___ |  \ ::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
2023-04-15 23-29-54 - Maxell GX Silver High Quality - Barbara - no label.mkv
[ACTION] Extracting audio track from video file
Traceback (most recent call last):
  File "c:\videotools\videotools.py", line 63, in <module>
    videoscanner.scanVideo(entry.name, args.directory)
  File "c:\videotools\videoscanner.py", line 239, in scanVideo
    file_data, rgb_values, rgb_min_max = process_frames(videoFile, totalFrames, frameRate)
  File "c:\videotools\videoscanner.py", line 171, in process_frames
    audio = AudioSegment.from_file(videoFile)
  File "C:\Users\dege1\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\audio_segment.py", line 778, in from_file
    fix_wav_headers(p_out)
  File "C:\Users\dege1\AppData\Local\Programs\Python\Python310\lib\site-packages\pydub\audio_segment.py", line 142, in fix_wav_headers
    raise CouldntDecodeError("Unable to process >4GB files")
pydub.exceptions.CouldntDecodeError: Unable to process >4GB files
```

**Comment by dege13** [comment]
I tested a smaller file and got no error. Perhaps there really is a 4GB limit. I will test some more files and add them here.
3.95 GB MKV file - No error
4.15 GB MKV file - No error
4.35 GB MKV file - No error
4.50 GB MKV file - No error
5.00 GB MKV file - No error
6.12 GB MKV file - error

**Comment by MoeFwacky** [comment]
I wonder if this is an MKV specific issue? I've been processing mp4s between 50 and 100 GB without issue today.

**Comment by MoeFwacky** [comment]
I finally ran into it after processing a bunch of files, the file itself is 48GB, so I can only imagine it's an issue with the size of the audio file in memory after extracted. I'm looking into some a fix for it, though it will probably require a creative workaround.

**Comment by MoeFwacky** [comment]
I've pushed a fix for this one, though it does write a temp.wav to disk. I would prefer to handle it all in memory, but this works until I find a way to do so.

**Comment by MoeFwacky** [comment]
Okay so after pushing that last update, I hit this again on a particularly long (8 hour) file. So now I've set it up to split the audio into multiple parts and handle them in chunks to get around this. If you or somebody runs into this after this update, I may have to add an entry to the config to allow users to control how many it gets split into, but for now I think this will be effective enough to avoid hitting that limit.
