### ISSUE TITLE
Splitter - Duplicate clips sometimes happen for long/slow fades

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#3]
A simple example is the MGM lion at the start of a movie. It resulted in the same clip 3 times. I assume this is from a long/slow fade.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/3587941/232066891-35b7201e-c223-4bc7-93d9-342feadfb658.png">

In my opinion, this should be considered one clip, not three. I am not sure the best way to do this, but I can give suggestions/ideas that maybe could work. I think not getting a new clip that existing between the previous start and end times would work. But I could be wrong.

Here is a small video to reproduce with:
https://user-images.githubusercontent.com/3587941/232069980-11a0cb84-e3bd-4288-ab29-827e68d0e094.mp4

config.ini
```
[scenesplitter]
#Adjust divisor that determines adjusted RGB Threshold
Median Divisor = 3

#minimum number of seconds
Clip Minimum = 4
```
```
#RGB value at which scenes are cut
RGB Threshold = 16

#minimum number of seconds
Clip Minimum = 20

#maximum number of seconds
Clip Maximum = 140
```
```
#seconds to ignore at front of file
Front Buffer = 2 

#seconds to ignore at end of file
End Buffer = 2 
```

**Comment by MoeFwacky** [comment]
I was unable to duplicate this bug. When running the splitter on the sample file, it gave me 3 total files that appeared to be appropriately split along fade points.

**Comment by dege13** [comment]
I may have grabbed the wrong place with the lion on that recording. I have made a small sample file again which I have confirmed reproduced the issue. Let me know if you have any issue reproducing.

[2022-11-26 10-49-55 - testing.zip](https://github.com/MoeFwacky/videotools/files/11279688/2022-11-26.10-49-55.-.testing.zip)

**Comment by MoeFwacky** [comment]
I believe this bug has been fixed with the last update, give it a test and let me know how it goes

**Comment by dege13** [comment]
The issue I saw is gone.
